CORE-6411 Add Jenkinsfile
corda/kotlin-stdlib-jdk-osgi pull request #2
Opened 2022-08-31 13:01 UTC by E1P3

Ensure the release is automated using shared library pipeline

2022-08-31 13:20 UTC, chrisr3 reviewed
This cannot possibly be the final version?!

2022-08-31 13:20 UTC, chrisr3 commented on build.gradle
> +    version="00-test"+kotlin_version
This doesn't look right for the "main" branch.

2022-08-31 13:20 UTC, chrisr3 commented on Jenkinsfile
> +    )
For testing only?

2022-08-31 13:27 UTC, ronanbrowne commented on build.gradle
> +    version="00-test"+kotlin_version
@E1P3 +1 revert to original,  This was just for testing purposes.

2022-08-31 13:29 UTC, ronanbrowne commented on Jenkinsfile
> +    )
yes change to corda-dependencies please @E1P3

2022-08-31 13:30 UTC, ronanbrowne requested changes

2022-08-31 13:30 UTC, ronanbrowne commented on Jenkinsfile
> +@Library('corda-shared-build-pipeline-steps@CORE-6347/modifications-for-corda-gradle-plugins') _
This needs to point to 5.0 ( we wont merge till accompanying changes approved)

2022-09-04 11:24 UTC, chrisr3 approved these changes
LGTM

2022-09-20 07:59 UTC, ronanbrowne approved these changes
LGTM

2022-09-20 08:01 UTC, merged